# Generated by Django 4.0.4 on 2022-05-26 14:12

from django.db import migrations, models
import evalfract.models


class Migration(migrations.Migration):

    dependencies = [
        ('evalfract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='images'),
        ),
    ]
