# Generated by Django 4.0.4 on 2022-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalfract', '0002_uploadimagetest_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
