# Generated by Django 4.0.4 on 2022-05-26 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evalfract', '0003_alter_imagemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image_path',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='transformations',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
