# Generated by Django 4.0.4 on 2022-05-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalfract', '0004_remove_imagemodel_image_imagemodel_image_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('num_iteration', models.IntegerField()),
                ('dataset_filename', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('width', 'height', 'num_iteration')},
            },
        ),
    ]
